### ISSUE TITLE
Unexpected '=', expecting enf of file in $HOME/flake/hosts/home.nix

### ISSUE THREAD

**Issue by RodneyBrown** [MatthiasBenaets/nix-dotfiles#8]
In my $HOME/flake/hosts/home.nix file I'm getting the following error:

```
error: syntax error, unexpected '=', expecting end of file

       at /nix/store/nlnljhx8qhpqcbzajxx7za5q7dcfbnyv-source/hosts/home.nix:5:8:

            4|
            5|   home = {
             |        ^
            6|     username = "${user}";
(use '--show-trace' to show detailed location information)
```

I'm guessing the error may be in my $HOME/flake/hosts/default.nix but not sure where to look...

**Comment by MatthiasBenaets** [comment]
I cannot be 100% sure about this, since their is such little information, but this is most definitely just a syntax error in `~/flake/hosts/home.nix`.

The only ways I would be able to reproduce this is by:
1.  Closing the attrs set before `home = {`, which in this case is not really likely since the error is on line 5.
2. Forgetting to open the attrs set, which is more likely.

Check your code at the start, it should look something like this, the comment is probably where it's going wrong.
```nix
{ config, lib, pkgs, user, ... }:
{ # forgetting this one or prematurely closing it can cause the same "unexpected '=', expecting end of file" error
  home = {
    username = "${user}";
  };
}
```

**Comment by RodneyBrown** [comment]
Thanks for your response.  I enjoyed your NixOS Configuration video, it was very good.

Yes, Somehow I omitted the opening brace after "{ config.... }" but before "home"

Thanks again for your help and your video!
